### ISSUE TITLE
Rack app error handling request

### ISSUE THREAD

**Issue by codyrickman** [ncr/rack-proxy#112]
Hello, I am using Ruby 2.4.10, Rails 5 on WSL. I recently ran bundle update and now I get this error in rails when running ./bin/webpack-dev-server. If I don't run the dev webpack server, rails compiles it on its own fine, but it takes a long time. The reason I am posting here is because it seems the stack trace points to an error in the rack-proxy module. 

2023-01-26 13:16:13 -0500: Rack app error handling request { GET /packs/js/Index-e399cab7acd9e34522df.js }
#<NoMethodError: undefined method `then' for #<Array:0x00005621b5f99cf0>>
/home/codyrickman/.rvm/gems/ruby-2.4.10/gems/rack-proxy-0.7.6/lib/rack/proxy.rb:27:in `extract_http_request_headers'
/home/codyrickman/.rvm/gems/ruby-2.4.10/gems/rack-proxy-0.7.6/lib/rack/proxy.rb:115:in `perform_request'
/home/codyrickman/.rvm/gems/ruby-2.4.10/gems/webpacker-5.4.3/lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
/home/codyrickman/.rvm/gems/ruby-2.4.10/gems/rack-proxy-0.7.6/lib/rack/proxy.rb:87:in `call'
/home/codyrickman/.rvm/gems/ruby-2.4.10/gems/railties-5.2.8.1/lib/rails/engine.rb:524:in `call'
/home/codyrickman/.rvm/gems/ruby-2.4.10/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
/home/codyrickman/.rvm/gems/ruby-2.4.10/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
/home/codyrickman/.rvm/gems/ruby-2.4.10/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
/home/codyrickman/.rvm/gems/ruby-2.4.10/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
/home/codyrickman/.rvm/gems/ruby-2.4.10/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'

**Comment by artemas** [comment]
ruby 2.5.9, rails 5.1.7, rack-reverse-proxy master,
https://github.com/ncr/rack-proxy/commit/57ac1f2ea5739969ee2d14bcee43e4e01af1092f#diff-24f5261702ed156369e5777101fa0d8a67095c490512f4e7e97462da2d2f0532R27

have to lock on 0.7.4

**Comment by ncr** [comment]
The stack trace shows `.then` failing on Ruby 2.4.10. `Object#then` was added in Ruby 2.6, and the gemspec has required `>= 2.6` for some time. Upgrade your Ruby to a supported version and the error will go away. Closing.
